plugins {
	id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT'
}

dependencies {
	minecraft 'com.mojang:minecraft:26.2'
	implementation 'net.fabricmc:fabric-loader:0.19.5'
}

loom {
	decompilers {
		cfr {
			memory = 1024
		}
	}
	runs {
		server {
			vmArgs '-Xmx1G'
		}
	}
	serverOnlyMinecraftJar()
}
