# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@main
        with:
          cache: gradle
          distribution: graalvm
          java-version: 25
      - run: gradle build
      - uses: actions/upload-artifact@main
        with:
          compression-level: 9
          if-no-files-found: error
          path: |
            obfuscated/build/libs/obfuscated.jar
            unobfuscated/build/libs/unobfuscated.jar
on:
  pull_request:
  push:
    branches:
      - '*'
permissions:
  contents: read
